services:
  wareach_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-wareach_secure_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-wareach_production}
    volumes:
      - pgdata:/var/lib/postgresql/data

  wareach_redis:
    image: redis:7-alpine
    restart: always

  wareach_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      WHATSAPP_PHONE_NUMBER_ID: ${WHATSAPP_PHONE_NUMBER_ID}
      WHATSAPP_BUSINESS_ACCOUNT_ID: ${WHATSAPP_BUSINESS_ACCOUNT_ID}
      WHATSAPP_ACCESS_TOKEN: ${WHATSAPP_ACCESS_TOKEN}
      WHATSAPP_API_VERSION: ${WHATSAPP_API_VERSION:-v25.0}
      DATABASE_URL: ${DATABASE_URL:-postgresql://wareach_secure_user:password@wareach_db:5432/wareach_production?schema=public}
      REDIS_URL: ${REDIS_URL:-redis://wareach_redis:6379}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    restart: unless-stopped
    depends_on:
      - wareach_db
      - wareach_redis
    command: >
      sh -c "npx prisma db push && npm start"

  wareach_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - wareach_backend
    restart: unless-stopped

volumes:
  pgdata:
